from .database import connect, write_transaction
from .security import utc_now
from .repository import audit

TEMPLATES = {'dagang': ('Usaha Dagang',
            [('1000', 'Kas', 'CASH_BANK'),
             ('1010', 'Bank', 'CASH_BANK'),
             ('1100', 'Piutang Usaha', 'RECEIVABLE'),
             ('1150', 'Uang Muka Pembelian', 'ASSET'),
             ('1200', 'Persediaan Barang Dagang', 'ASSET'),
             ('1250', 'PPN Masukan', 'ASSET'),
             ('1300', 'Perlengkapan Toko', 'ASSET'),
             ('1400', 'Aktiva Tetap', 'ASSET'),
             ('1410', 'Akumulasi Penyusutan', 'ASSET'),
             ('2000', 'Hutang Usaha', 'PAYABLE'),
             ('2100', 'PPN Keluaran', 'LIABILITY'),
             ('2200', 'Uang Muka Penjualan', 'LIABILITY'),
             ('3000', 'Modal Pemilik', 'EQUITY'),
             ('3100', 'Prive', 'EQUITY'),
             ('3200', 'Laba Ditahan', 'EQUITY'),
             ('4000', 'Penjualan Barang', 'REVENUE'),
             ('4100', 'Retur Penjualan', 'REVENUE'),
             ('4200', 'Pendapatan Lain-lain', 'REVENUE'),
             ('5000', 'Harga Pokok Penjualan', 'HPP'),
             ('5100', 'Beban Gaji', 'OPERATING_EXPENSE'),
             ('5110', 'Beban Sewa', 'OPERATING_EXPENSE'),
             ('5120', 'Beban Listrik dan Air', 'OPERATING_EXPENSE'),
             ('5130', 'Beban Transportasi', 'OPERATING_EXPENSE'),
             ('5200', 'Beban Penyusutan', 'OPERATING_EXPENSE')]),
 'jasa': ('Perusahaan Jasa',
          [('1000', 'Kas', 'CASH_BANK'),
           ('1010', 'Bank', 'CASH_BANK'),
           ('1100', 'Piutang Jasa', 'RECEIVABLE'),
           ('1150', 'Uang Muka Biaya', 'ASSET'),
           ('1300', 'Perlengkapan Kantor', 'ASSET'),
           ('1400', 'Peralatan dan Aktiva Tetap', 'ASSET'),
           ('1410', 'Akumulasi Penyusutan', 'ASSET'),
           ('2000', 'Hutang Usaha', 'PAYABLE'),
           ('2200', 'Pendapatan Diterima Dimuka', 'LIABILITY'),
           ('3000', 'Modal Pemilik', 'EQUITY'),
           ('3100', 'Prive', 'EQUITY'),
           ('3200', 'Laba Ditahan', 'EQUITY'),
           ('4000', 'Pendapatan Jasa', 'REVENUE'),
           ('4100', 'Pendapatan Konsultasi', 'REVENUE'),
           ('4200', 'Pendapatan Lain-lain', 'REVENUE'),
           ('5000', 'Biaya Langsung Jasa', 'HPP'),
           ('5100', 'Beban Gaji', 'OPERATING_EXPENSE'),
           ('5110', 'Beban Sewa', 'OPERATING_EXPENSE'),
           ('5120', 'Beban Telekomunikasi', 'OPERATING_EXPENSE'),
           ('5130', 'Beban Transportasi', 'OPERATING_EXPENSE'),
           ('5200', 'Beban Penyusutan', 'OPERATING_EXPENSE')]),
 'bengkel': ('Bengkel',
             [('1000', 'Kas Bengkel', 'CASH_BANK'),
              ('1010', 'Bank', 'CASH_BANK'),
              ('1100', 'Piutang Pelanggan', 'RECEIVABLE'),
              ('1200', 'Persediaan Suku Cadang', 'ASSET'),
              ('1210', 'Persediaan Oli dan Bahan', 'ASSET'),
              ('1300', 'Peralatan Bengkel', 'ASSET'),
              ('1310', 'Kendaraan Operasional', 'ASSET'),
              ('1410', 'Akumulasi Penyusutan', 'ASSET'),
              ('2000', 'Hutang Pemasok Suku Cadang', 'PAYABLE'),
              ('2100', 'Hutang Gaji Mekanik', 'LIABILITY'),
              ('3000', 'Modal Pemilik', 'EQUITY'),
              ('3200', 'Laba Ditahan', 'EQUITY'),
              ('4000', 'Pendapatan Jasa Servis', 'REVENUE'),
              ('4010', 'Penjualan Suku Cadang', 'REVENUE'),
              ('4020', 'Pendapatan Jasa Cuci', 'REVENUE'),
              ('5000', 'HPP Suku Cadang', 'HPP'),
              ('5010', 'Upah Langsung Mekanik', 'HPP'),
              ('5100', 'Beban Gaji', 'OPERATING_EXPENSE'),
              ('5110', 'Beban Listrik Bengkel', 'OPERATING_EXPENSE'),
              ('5120', 'Beban Peralatan Kecil', 'OPERATING_EXPENSE'),
              ('5200', 'Beban Penyusutan', 'OPERATING_EXPENSE')]),
 'sekolah': ('Sekolah / Lembaga Pendidikan',
             [('1000', 'Kas Sekolah', 'CASH_BANK'),
              ('1010', 'Bank Sekolah', 'CASH_BANK'),
              ('1100', 'Piutang SPP', 'RECEIVABLE'),
              ('1110', 'Piutang Uang Kegiatan', 'RECEIVABLE'),
              ('1200', 'Persediaan Buku dan Seragam', 'ASSET'),
              ('1300', 'Perlengkapan Pendidikan', 'ASSET'),
              ('1400', 'Gedung dan Peralatan Sekolah', 'ASSET'),
              ('1410', 'Akumulasi Penyusutan', 'ASSET'),
              ('2000', 'Hutang Usaha', 'PAYABLE'),
              ('2100', 'Pendapatan Diterima Dimuka', 'LIABILITY'),
              ('3000', 'Dana/Modal Yayasan', 'EQUITY'),
              ('3200', 'Saldo Dana', 'EQUITY'),
              ('4000', 'Pendapatan SPP', 'REVENUE'),
              ('4010', 'Pendapatan Uang Pangkal', 'REVENUE'),
              ('4020', 'Pendapatan Kegiatan', 'REVENUE'),
              ('4030', 'Pendapatan Buku dan Seragam', 'REVENUE'),
              ('5000', 'Beban Langsung Pendidikan', 'HPP'),
              ('5100', 'Beban Gaji Guru dan Karyawan', 'OPERATING_EXPENSE'),
              ('5110', 'Beban Listrik dan Internet', 'OPERATING_EXPENSE'),
              ('5120', 'Beban Pemeliharaan', 'OPERATING_EXPENSE'),
              ('5200', 'Beban Penyusutan', 'OPERATING_EXPENSE')]),
 'pabrik': ('Pabrik / Manufaktur',
            [('1000', 'Kas', 'CASH_BANK'),
             ('1010', 'Bank', 'CASH_BANK'),
             ('1100', 'Piutang Usaha', 'RECEIVABLE'),
             ('1200', 'Persediaan Bahan Baku', 'ASSET'),
             ('1210', 'Persediaan Barang Dalam Proses', 'ASSET'),
             ('1220', 'Persediaan Barang Jadi', 'ASSET'),
             ('1230', 'Persediaan Bahan Penolong', 'ASSET'),
             ('1400', 'Mesin dan Peralatan Pabrik', 'ASSET'),
             ('1410', 'Akumulasi Penyusutan Mesin', 'ASSET'),
             ('2000', 'Hutang Usaha', 'PAYABLE'),
             ('2100', 'Hutang Biaya Produksi', 'LIABILITY'),
             ('3000', 'Modal', 'EQUITY'),
             ('3200', 'Laba Ditahan', 'EQUITY'),
             ('4000', 'Penjualan Produk Jadi', 'REVENUE'),
             ('4100', 'Penjualan Limbah Produksi', 'REVENUE'),
             ('5000', 'Pemakaian Bahan Baku', 'HPP'),
             ('5010', 'Tenaga Kerja Langsung', 'HPP'),
             ('5020', 'Overhead Pabrik', 'HPP'),
             ('5030', 'HPP Produk Jadi', 'HPP'),
             ('5100', 'Beban Gaji Administrasi', 'OPERATING_EXPENSE'),
             ('5110', 'Beban Penjualan', 'OPERATING_EXPENSE'),
             ('5200', 'Beban Penyusutan', 'OPERATING_EXPENSE')]),
 'perkebunan': ('Perkebunan',
                [('1000', 'Kas Kebun', 'CASH_BANK'),
                 ('1010', 'Bank', 'CASH_BANK'),
                 ('1100', 'Piutang Hasil Kebun', 'RECEIVABLE'),
                 ('1200', 'Persediaan Pupuk dan Pestisida', 'ASSET'),
                 ('1210', 'Persediaan Hasil Panen', 'ASSET'),
                 ('1300', 'Tanaman Belum Menghasilkan', 'ASSET'),
                 ('1310', 'Tanaman Menghasilkan', 'ASSET'),
                 ('1400', 'Alat dan Mesin Pertanian', 'ASSET'),
                 ('1410', 'Akumulasi Penyusutan', 'ASSET'),
                 ('2000', 'Hutang Pemasok', 'PAYABLE'),
                 ('2100', 'Hutang Upah Pekerja', 'LIABILITY'),
                 ('3000', 'Modal', 'EQUITY'),
                 ('3200', 'Laba Ditahan', 'EQUITY'),
                 ('4000', 'Penjualan Hasil Panen', 'REVENUE'),
                 ('4100', 'Pendapatan Sampingan Kebun', 'REVENUE'),
                 ('5000', 'Biaya Pemeliharaan Tanaman', 'HPP'),
                 ('5010', 'Biaya Panen', 'HPP'),
                 ('5020', 'Biaya Pengolahan Hasil', 'HPP'),
                 ('5100', 'Beban Gaji Administrasi', 'OPERATING_EXPENSE'),
                 ('5110', 'Beban Transportasi', 'OPERATING_EXPENSE'),
                 ('5200', 'Beban Penyusutan', 'OPERATING_EXPENSE')]),
 'warung': ('Warung / Toko Kecil',
            [('1000', 'Kas Warung', 'CASH_BANK'),
             ('1010', 'Bank / E-Wallet', 'CASH_BANK'),
             ('1100', 'Piutang Pelanggan', 'RECEIVABLE'),
             ('1200', 'Persediaan Barang Warung', 'ASSET'),
             ('1300', 'Peralatan Warung', 'ASSET'),
             ('1400', 'Etalase dan Peralatan', 'ASSET'),
             ('1410', 'Akumulasi Penyusutan', 'ASSET'),
             ('2000', 'Hutang Pemasok', 'PAYABLE'),
             ('3000', 'Modal Pemilik', 'EQUITY'),
             ('3100', 'Prive', 'EQUITY'),
             ('3200', 'Laba Ditahan', 'EQUITY'),
             ('4000', 'Penjualan', 'REVENUE'),
             ('4100', 'Pendapatan Lain-lain', 'REVENUE'),
             ('5000', 'Harga Pokok Penjualan', 'HPP'),
             ('5100', 'Beban Listrik', 'OPERATING_EXPENSE'),
             ('5110', 'Beban Sewa', 'OPERATING_EXPENSE'),
             ('5120', 'Beban Transportasi', 'OPERATING_EXPENSE'),
             ('5130', 'Beban Administrasi', 'OPERATING_EXPENSE'),
             ('5200', 'Beban Penyusutan', 'OPERATING_EXPENSE')]),
 'apotik': ('Apotek',
            [('1000', 'Kas Apotek', 'CASH_BANK'),
             ('1010', 'Bank', 'CASH_BANK'),
             ('1100', 'Piutang Pelanggan/Asuransi', 'RECEIVABLE'),
             ('1200', 'Persediaan Obat', 'ASSET'),
             ('1210', 'Persediaan Alat Kesehatan', 'ASSET'),
             ('1220', 'Persediaan Obat Kedaluwarsa/Rusak', 'ASSET'),
             ('1300', 'Perlengkapan Apotek', 'ASSET'),
             ('1400', 'Peralatan Apotek', 'ASSET'),
             ('1410', 'Akumulasi Penyusutan', 'ASSET'),
             ('2000', 'Hutang Distributor Obat', 'PAYABLE'),
             ('2100', 'Hutang Pajak', 'LIABILITY'),
             ('3000', 'Modal', 'EQUITY'),
             ('3200', 'Laba Ditahan', 'EQUITY'),
             ('4000', 'Penjualan Obat', 'REVENUE'),
             ('4010', 'Penjualan Alat Kesehatan', 'REVENUE'),
             ('4020', 'Pendapatan Jasa Resep', 'REVENUE'),
             ('5000', 'HPP Obat', 'HPP'),
             ('5010', 'HPP Alat Kesehatan', 'HPP'),
             ('5100', 'Beban Gaji Apoteker', 'OPERATING_EXPENSE'),
             ('5110', 'Beban Sewa', 'OPERATING_EXPENSE'),
             ('5120', 'Beban Listrik', 'OPERATING_EXPENSE'),
             ('5200', 'Beban Penyusutan', 'OPERATING_EXPENSE')]),
 'distributor': ('Distributor',
                 [('1000', 'Kas', 'CASH_BANK'),
                  ('1010', 'Bank', 'CASH_BANK'),
                  ('1100', 'Piutang Distributor', 'RECEIVABLE'),
                  ('1110', 'Cadangan Kerugian Piutang', 'ASSET'),
                  ('1200', 'Persediaan Barang Distribusi', 'ASSET'),
                  ('1210', 'Barang Dalam Perjalanan', 'ASSET'),
                  ('1300', 'Uang Muka Pemasok', 'ASSET'),
                  ('1400', 'Kendaraan Distribusi', 'ASSET'),
                  ('1410', 'Akumulasi Penyusutan', 'ASSET'),
                  ('2000', 'Hutang Pemasok', 'PAYABLE'),
                  ('2100', 'Hutang Ekspedisi', 'LIABILITY'),
                  ('2200', 'Uang Muka Pelanggan', 'LIABILITY'),
                  ('3000', 'Modal', 'EQUITY'),
                  ('3200', 'Laba Ditahan', 'EQUITY'),
                  ('4000', 'Penjualan Distribusi', 'REVENUE'),
                  ('4100', 'Retur dan Potongan Penjualan', 'REVENUE'),
                  ('5000', 'Harga Pokok Penjualan', 'HPP'),
                  ('5010', 'Biaya Angkut Pembelian', 'HPP'),
                  ('5100', 'Beban Gaji Sales', 'OPERATING_EXPENSE'),
                  ('5110', 'Beban Komisi Sales', 'OPERATING_EXPENSE'),
                  ('5120', 'Beban Pengiriman', 'OPERATING_EXPENSE'),
                  ('5200', 'Beban Penyusutan', 'OPERATING_EXPENSE')]),
 'kontraktor': ('Kontraktor',
                [('1000', 'Kas', 'CASH_BANK'),
                 ('1010', 'Bank', 'CASH_BANK'),
                 ('1100', 'Piutang Termin Proyek', 'RECEIVABLE'),
                 ('1110', 'Retensi Piutang', 'RECEIVABLE'),
                 ('1200', 'Persediaan Material', 'ASSET'),
                 ('1210', 'Pekerjaan Dalam Proses', 'ASSET'),
                 ('1220', 'Uang Muka Subkontraktor', 'ASSET'),
                 ('1300', 'Biaya Dibayar Dimuka', 'ASSET'),
                 ('1400', 'Peralatan Proyek', 'ASSET'),
                 ('1410', 'Akumulasi Penyusutan', 'ASSET'),
                 ('2000', 'Hutang Supplier', 'PAYABLE'),
                 ('2010', 'Hutang Subkontraktor', 'PAYABLE'),
                 ('2100', 'Retensi Hutang', 'LIABILITY'),
                 ('2200', 'Uang Muka Pelanggan', 'LIABILITY'),
                 ('3000', 'Modal', 'EQUITY'),
                 ('3200', 'Laba Ditahan', 'EQUITY'),
                 ('4000', 'Pendapatan Kontrak', 'REVENUE'),
                 ('4010', 'Pendapatan Variasi Pekerjaan', 'REVENUE'),
                 ('5000', 'Biaya Material Proyek', 'HPP'),
                 ('5010', 'Biaya Tenaga Kerja Proyek', 'HPP'),
                 ('5020', 'Biaya Subkontraktor', 'HPP'),
                 ('5030', 'Biaya Overhead Proyek', 'HPP'),
                 ('5100', 'Beban Administrasi Kantor', 'OPERATING_EXPENSE'),
                 ('5200', 'Beban Penyusutan', 'OPERATING_EXPENSE')]),
 'kontraktor_bangunan': ('Kontraktor Bangunan / Sipil', [
   ('1000','Kas Proyek','CASH_BANK'),('1010','Bank Operasional Proyek','CASH_BANK'),('1100','Piutang Termin Proyek','RECEIVABLE'),('1110','Retensi Piutang','RECEIVABLE'),
   ('1200','Persediaan Material Proyek','ASSET'),('1210','Pekerjaan Dalam Proses Proyek','ASSET'),('1220','Uang Muka Supplier/Subkon','ASSET'),('1400','Peralatan Proyek','ASSET'),
   ('2000','Hutang Supplier Material','PAYABLE'),('2010','Hutang Subkontraktor','PAYABLE'),('2100','Retensi Hutang Subkon','LIABILITY'),('2200','Uang Muka Pemberi Kerja','LIABILITY'),
   ('3000','Modal','EQUITY'),('3200','Laba Ditahan','EQUITY'),('4000','Pendapatan Termin Proyek','REVENUE'),('4010','Pendapatan Variation Order','REVENUE'),
   ('5000','Biaya Material Proyek','HPP'),('5010','Biaya Tenaga Kerja Proyek','HPP'),('5020','Biaya Subkontraktor','HPP'),('5030','Biaya Alat & Sewa Proyek','HPP'),('5040','Biaya Overhead Lapangan','HPP'),
   ('5100','Beban Gaji Kantor','OPERATING_EXPENSE'),('5110','Beban Kantor & Administrasi','OPERATING_EXPENSE'),('5120','Beban Kendaraan & Transport','OPERATING_EXPENSE'),('5200','Beban Penyusutan','OPERATING_EXPENSE')]),
 'kontraktor_interior': ('Kontraktor Interior / Renovasi', [
   ('1000','Kas','CASH_BANK'),('1010','Bank','CASH_BANK'),('1100','Piutang Termin Interior','RECEIVABLE'),('1110','Retensi Piutang','RECEIVABLE'),('1200','Persediaan Material Interior','ASSET'),('1210','Pekerjaan Dalam Proses','ASSET'),
   ('2000','Hutang Supplier','PAYABLE'),('2010','Hutang Tukang/Subkon','PAYABLE'),('3000','Modal','EQUITY'),('3200','Laba Ditahan','EQUITY'),('4000','Pendapatan Proyek Interior','REVENUE'),('4010','Pendapatan Pekerjaan Tambah','REVENUE'),
   ('5000','Material Interior','HPP'),('5010','Upah Tukang','HPP'),('5020','Biaya Subkon Interior','HPP'),('5030','Biaya Pengiriman & Mobilisasi','HPP'),('5040','Biaya Site/Overhead Proyek','HPP'),('5100','Beban Administrasi','OPERATING_EXPENSE'),('5200','Beban Penyusutan','OPERATING_EXPENSE')]),
 'kontraktor_mep': ('Kontraktor MEP / Instalasi', [
   ('1000','Kas','CASH_BANK'),('1010','Bank','CASH_BANK'),('1100','Piutang Termin MEP','RECEIVABLE'),('1110','Retensi Piutang','RECEIVABLE'),('1200','Persediaan Material MEP','ASSET'),('1210','Pekerjaan Dalam Proses MEP','ASSET'),
   ('2000','Hutang Supplier MEP','PAYABLE'),('2010','Hutang Subkon MEP','PAYABLE'),('3000','Modal','EQUITY'),('3200','Laba Ditahan','EQUITY'),('4000','Pendapatan Proyek MEP','REVENUE'),('4010','Pendapatan Testing/Commissioning','REVENUE'),
   ('5000','Material MEP','HPP'),('5010','Tenaga Kerja Instalasi','HPP'),('5020','Subkon MEP','HPP'),('5030','Sewa Alat & Testing','HPP'),('5040','Overhead Lapangan MEP','HPP'),('5100','Beban Administrasi','OPERATING_EXPENSE'),('5200','Beban Penyusutan','OPERATING_EXPENSE')]),
 'developer_properti': ('Developer Properti / Proyek', [
   ('1000','Kas','CASH_BANK'),('1010','Bank','CASH_BANK'),('1100','Piutang Penjualan Unit','RECEIVABLE'),('1150','Piutang KPR Dalam Proses','RECEIVABLE'),('1200','Persediaan Tanah','ASSET'),('1210','Bangunan Dalam Proses','ASSET'),('1220','Persediaan Unit Siap Jual','ASSET'),
   ('2000','Hutang Kontraktor/Supplier','PAYABLE'),('2100','Uang Muka Konsumen','LIABILITY'),('3000','Modal','EQUITY'),('3200','Laba Ditahan','EQUITY'),('4000','Penjualan Unit Properti','REVENUE'),('4010','Pendapatan Lain Proyek','REVENUE'),
   ('5000','HPP Tanah','HPP'),('5010','Biaya Konstruksi','HPP'),('5020','Biaya Infrastruktur','HPP'),('5030','Biaya Perizinan Proyek','HPP'),('5100','Beban Marketing','OPERATING_EXPENSE'),('5110','Beban Administrasi','OPERATING_EXPENSE'),('5200','Beban Penyusutan','OPERATING_EXPENSE')])}

TYPE_MAP={
'CASH_BANK':('ASSET','DEBIT'),'RECEIVABLE':('ASSET','DEBIT'),'ASSET':('ASSET','DEBIT'),
'PAYABLE':('LIABILITY','CREDIT'),'LIABILITY':('LIABILITY','CREDIT'),
'EQUITY':('EQUITY','CREDIT'),'REVENUE':('REVENUE','CREDIT'),
'HPP':('EXPENSE','DEBIT'),'OPERATING_EXPENSE':('EXPENSE','DEBIT')}

def list_templates():
    order=['dagang','jasa','bengkel','sekolah','pabrik','perkebunan','warung','apotik','distributor','kontraktor']
    type_help={'CASH_BANK':'Kas/Bank (Aset Lancar)','RECEIVABLE':'Piutang (Aset Lancar)','ASSET':'Aset','PAYABLE':'Hutang (Kewajiban)','LIABILITY':'Kewajiban','EQUITY':'Ekuitas/Modal','REVENUE':'Pendapatan','HPP':'Harga Pokok Penjualan','OPERATING_EXPENSE':'Beban Operasional'}
    return [{'key':k,'name':TEMPLATES[k][0],'account_count':len(TEMPLATES[k][1]),'subtypes':sorted(set(x[2] for x in TEMPLATES[k][1])),'type_help':type_help} for k in order if k in TEMPLATES]

def preview(template_key):
    if template_key not in TEMPLATES:
        raise ValueError('Standar usaha tidak valid.')
    name,accounts=TEMPLATES[template_key]
    c=connect()
    try:
        existing={str(r['code']).upper():dict(r) for r in c.execute('SELECT id,code,name,account_subtype FROM chart_of_accounts').fetchall()}
    finally:
        c.close()
    items=[]
    for code,account_name,subtype in accounts:
        old=existing.get(code.upper())
        items.append({'code':code,'name':account_name,'account_subtype':subtype,'status':'EXISTS' if old else 'NEW','existing_name':old['name'] if old else None})
    return {'key':template_key,'name':name,'items':items,'new_count':sum(x['status']=='NEW' for x in items),'existing_count':sum(x['status']=='EXISTS' for x in items)}

def apply_template(actor,template_key,ip):
    result=preview(template_key)
    now=utc_now()
    created=[]
    skipped=[]
    with write_transaction() as tx:
        for item in result['items']:
            if item['status']=='EXISTS':
                skipped.append(item['code'])
                continue
            atype,normal=TYPE_MAP[item['account_subtype']]
            cur=tx.execute("INSERT INTO chart_of_accounts(code,name,account_type,account_subtype,normal_balance,parent_id,is_system,is_active,created_at,updated_at) VALUES(?,?,?,?,?,NULL,0,1,?,?)",(item['code'],item['name'],atype,item['account_subtype'],normal,now,now))
            created.append({'id':cur.lastrowid,'code':item['code'],'name':item['name']})
        audit(actor['id'],'COA_TEMPLATE_APPLIED','coa_template',None,{'template':template_key,'created':len(created),'skipped':len(skipped)},ip,tx)
    return {'template':result['name'],'created':created,'created_count':len(created),'skipped_codes':skipped,'skipped_count':len(skipped)}
