PRODUCT_NAME = 'StokLedger Online'
APP_ID = 'STOKLEDGER-PRO-ULTIMA-WEB'
LICENSE_FILENAME = 'STOKLEDGER_ONLINE.LIC'
IS_ULTIMA = True
VERSION = "1.4.2-password-recovery-pg"
DESKTOP_BASE_VERSION = "1.22.55"
