PRODUCT_NAME = 'StokLedger Pro Ultima Web'
APP_ID = 'STOKLEDGER-PRO-ULTIMA-WEB'
LICENSE_FILENAME = 'STOKLEDGER_PRO_ULTIMA_WEB.LIC'
IS_ULTIMA = True
VERSION = "1.3.0-web-saas"
DESKTOP_BASE_VERSION = "1.22.55"
